services:
  webtoon-api:
    env_file:
      - ./app/webtoon-api/env/local.env
    image: webtoon-api:latest
    build:
      context: .
      dockerfile: app/webtoon-api/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    networks:
      - webtoon
  media-file-api:
    env_file:
      - ./app/media-file-api/env/local.env
    image: media-file-api:latest
    build:
      context: .
      dockerfile: app/media-file-api/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    networks:
      - webtoon
  db:
    image: webtoon-db:latest
    build:
      context: ./db
      dockerfile: mysql/Dockerfile
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      start_period: 10s
    networks:
      - webtoon
    ports:
      - "3307:3306"
  flyway:
    env_file:
      - ./db/flyway/env/local.env
    image: webtoon-flyway:latest
    build:
      context: ./db/flyway
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    command: migrate
    networks:
      - webtoon
networks:
  webtoon:
    driver: bridge
